services:
  neo4j:
    image: neo4j:5.24-community
    networks:
      - internal
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
  socketio:
    image: ghcr.io/azishio/nahlun-socketio:latest
    networks:
      - internal
  server:
    image: ghcr.io/azishio/nahlun-server:latest
    networks:
      - internal
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_DB=neo4j
      - NEO4J_URI=localhost:7687
networks:
  internal:
    driver: bridge
