services:
  neo4j:
    image: neo4j:5.24-community
    networks:
      - internal
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4JLABS_PLUGINS=["apoc"]
      - EXTENSION_SCRIPT=/scripts/neo4j_extension_script.sh
    env_file:
      - /etc/nahlund/neo4j.env
    volumes:
      - nahlun-neo4j-data:/data
      - nahlun-neo4j-logs:/logs
      - /opt/nahlund/neo4j_scripts:/scripts
      - /etc/nahlund/import:/import
  socketio:
    image: ghcr.io/azishio/nahlun-socketio:latest
    networks:
      - internal
    env_file:
      - /etc/nahlund/socketio.env
  server:
    image: ghcr.io/azishio/nahlun-server:latest
    networks:
      - internal
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_DB=neo4j
      - NEO4J_URI=localhost:7687
      - DISK_CACHE_BASE_PATH=/var/cache
    env_file:
      - /etc/nahlund/server.env
    volumes:
      - nahlun-disk-cache:/var/cache
networks:
  internal:
    driver: bridge
volumes:
  nahlun-neo4j-data:
  nahlun-neo4j-logs:
  nahlun-disk-cache:
